services:
  db:
    image: mysql/mysql-server:5.7
    container_name: microblog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root1234" 
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: "456456"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u microblog -p456456 -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  prod:
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    container_name: microblog-prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://microblog:456456@db:3306/microblog"
      FLASK_ENV: "production"
      FLASH_APP: "microblog:app"
    ports:
      - "5000:5000"

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile_test
    container_name: microblog-test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://microblog:456456@db:3306/microblog"
      FLASK_ENV: "testing"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: /test-entrypoint.sh
