---
sg_groups:
    -   name: loadbalancer
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTPS
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: appserver
        port_rules:
        -   name: APP
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 8000
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: "{{ hostvars[groups['myloadbalancer'][0]].ansible_host }}/32"
    -   name: database
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: MYSQL_app1
            protocol: Tcp
            destination_port_range: 3306
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: "{{ hostvars[groups['myappserver'][0]].ansible_host }}/32"
        -   name: MYSQL_app2
            protocol: Tcp
            destination_port_range: 3306
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: "{{ hostvars[groups['myappserver'][1]].ansible_host }}/32"
    -   name: monitoring
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: Prometheus
            protocol: Tcp
            destination_port_range: 9090
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: Grafana
            protocol: Tcp
            destination_port_range: 3000
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: Alertmanager
            protocol: Tcp
            destination_port_range: 9093
            access: Allow
            priority: 1004
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: NodeExporter
            protocol: Tcp
            destination_port_range: 9100
            access: Allow
            priority: 1005
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'